/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package createpage;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ARGHYAJIT
 */
public class newmember extends javax.swing.JFrame {
int ph,ag;
String nm,add,em,pwd,rpwd,fa,ma;
Connection con;
PreparedStatement pst;
    /**
     * Creates new form newmember
     */
    public newmember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        T7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        T4 = new javax.swing.JTextField();
        T5 = new javax.swing.JTextField();
        T6 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        P1 = new javax.swing.JPasswordField();
        P2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        t3 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(32, 260, 76, 19);
        getContentPane().add(T1);
        T1.setBounds(32, 292, 210, 22);

        jLabel3.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Phone Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(32, 349, 153, 19);

        jLabel4.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 204));
        jLabel4.setText("Email-Adress");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(32, 420, 143, 19);

        jLabel6.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 204));
        jLabel6.setText("Adress");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(412, 420, 88, 19);

        jLabel2.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 204));
        jLabel2.setText("Father Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(32, 497, 129, 19);

        jLabel9.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 204));
        jLabel9.setText("Password");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(412, 516, 119, 19);

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 255, 204));
        jLabel13.setText("Mother Name");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(412, 258, 150, 26);

        jLabel14.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 255, 204));
        jLabel14.setText("Age");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(412, 349, 35, 19);

        jLabel10.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 204));
        jLabel10.setText("Re-Passsword");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(412, 587, 139, 19);
        getContentPane().add(T4);
        T4.setBounds(32, 534, 210, 22);
        getContentPane().add(T5);
        T5.setBounds(412, 292, 210, 22);
        getContentPane().add(T6);
        T6.setBounds(412, 386, 210, 22);
        getContentPane().add(T2);
        T2.setBounds(32, 386, 210, 22);
        getContentPane().add(P1);
        P1.setBounds(412, 547, 210, 22);
        getContentPane().add(P2);
        P2.setBounds(412, 647, 210, 22);

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\JAVA Jframe\\Book1\\folder-blue-click-icon.png")); // NOI18N
        jButton1.setText("Click");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(667, 624, 144, 70);

        jButton2.setIcon(new javax.swing.ImageIcon("D:\\JAVA Jframe\\Book1\\lock-reset-icon.png")); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(877, 624, 121, 78);
        getContentPane().add(t3);
        t3.setBounds(32, 457, 210, 22);
        getContentPane().add(t7);
        t7.setBounds(412, 451, 210, 53);

        jLabel5.setFont(new java.awt.Font("Stencil", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\JAVA Jframe\\Book1\\Actions-contact-new-icon23.png")); // NOI18N
        jLabel5.setText("                  NEW MEMBER");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(12, 14, 850, 232);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(12, 8, 0, 0);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1065, 14, 0, 0);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(6, 14, 0, 0);

        jButton3.setIcon(new javax.swing.ImageIcon("D:\\JAVA Jframe\\Book1\\Actions-application-exit-icon.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1180, 20, 88, 78);

        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\JAVA Jframe\\Book1\\639a19acd100de28334bca32_Golds-gym-3d-scanning.jpeg")); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 1280, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                        
    try{
        Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gym?useSSL=false","root","Arghyajit12@");
            {
    nm=T1.getText();
    ph=Integer.parseInt(T2.getText());
    em=t3.getText();
    fa=T4.getText();
    ma=T5.getText();
    ag=Integer.parseInt(T6.getText());
    add=t7.getText();
   // ag=Integer.parseInt(t8.getText());
  // dd=(((JTextField)d1.getDateEditor().getUiComponent()).getText());
     pwd=P1.getText();
    rpwd=P2.getText();
    if(rpwd.equals(pwd))
    { 
String sql;
sql="insert into g1 values('"+nm+"','"+ph+"','"+em+"','"+fa+"','"+ma+"','"+ag+"','"+add+"','"+pwd+"')";
pst=con.prepareStatement(sql);
int x=pst.executeUpdate();
System.out.print("hi");
            if(x==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Registration sucess");
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Registration not sucess");
                }
    else
        JOptionPane.showMessageDialog(rootPane, "Password not Match");
    }
    }
    catch(Exception e)
    {
        System.out.print(e);
    }// TODO add your handling code here:                                   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
T1.setText("");      
T2.setText("");
t3.setText("");
T4.setText("");
T5.setText("");
T6.setText("");
t7.setText("");
P1.setText("");
P2.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new newmember().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField P1;
    private javax.swing.JPasswordField P2;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t7;
    // End of variables declaration//GEN-END:variables

    private void setvisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
